// <auto-generated />
using System;
using Examen_Desarrollador.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Examen_Desarrollador.Migrations
{
    [DbContext(typeof(DBcontext))]
    partial class DBcontextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Examen_Desarrollador.Entitys.Articulo", b =>
                {
                    b.Property<int>("Articulo_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Articulo_id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Articulo_id");

                    b.ToTable("Articulos");
                });

            modelBuilder.Entity("Examen_Desarrollador.Entitys.Articulo_tienda", b =>
                {
                    b.Property<int>("Articulo_id")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("Tienda_id")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.HasKey("Articulo_id", "Tienda_id");

                    b.ToTable("TiendaArticulos");
                });

            modelBuilder.Entity("Examen_Desarrollador.Entitys.Cliente", b =>
                {
                    b.Property<int>("Cliente_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Cliente_id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Cliente_id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Examen_Desarrollador.Entitys.Cliente_articulo", b =>
                {
                    b.Property<int>("Cliente_id")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("Articulo_id")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.HasKey("Cliente_id", "Articulo_id");

                    b.HasIndex("Articulo_id");

                    b.ToTable("ClienteArticulos");
                });

            modelBuilder.Entity("Examen_Desarrollador.Entitys.Tienda", b =>
                {
                    b.Property<int>("Tienda_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Tienda_id"));

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Tienda_id");

                    b.ToTable("Tiendas");
                });

            modelBuilder.Entity("Examen_Desarrollador.Entitys.Articulo_tienda", b =>
                {
                    b.HasOne("Examen_Desarrollador.Entitys.Articulo", null)
                        .WithMany("TiendaArticulos")
                        .HasForeignKey("Articulo_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Examen_Desarrollador.Entitys.Cliente_articulo", b =>
                {
                    b.HasOne("Examen_Desarrollador.Entitys.Articulo", null)
                        .WithMany("ClienteArticulos")
                        .HasForeignKey("Articulo_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Examen_Desarrollador.Entitys.Cliente", null)
                        .WithMany("Cliente_articulos")
                        .HasForeignKey("Cliente_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Examen_Desarrollador.Entitys.Articulo", b =>
                {
                    b.Navigation("ClienteArticulos");

                    b.Navigation("TiendaArticulos");
                });

            modelBuilder.Entity("Examen_Desarrollador.Entitys.Cliente", b =>
                {
                    b.Navigation("Cliente_articulos");
                });
#pragma warning restore 612, 618
        }
    }
}
